NUM_AUDIO = 22
NUM_QUESTIONS_PER_AUDIO = 4
NUM_EXTRA_QUESTIONS = 0
EXTRA_QUESTIONS_INDEX = []
NUM_QUESTIONS = NUM_AUDIO * NUM_QUESTIONS_PER_AUDIO + NUM_EXTRA_QUESTIONS
QUESTION_TYPES = ['vocal_timbre_rating', 'overall_rating', 'genre_rating', 'mood_rating']